Repository VisorFolks/cyancore, pull requests merged in 2021-10, with the labels that each got.

#41 <LibNMath> Added new function to neomath library
  jenkins.pipe
  src/lib/libnmath/include/nmath.h
  src/lib/libnmath/nmath.c
Labels: documentation, enhancement, cyancore framework

#57 (Console) Bug fix for membuf & Uart
  src/driver/console/console_membuf/console_membuf.c
  src/platform/mega_avr/common/hal/uart/uart.c
Labels: terravisor, bug-low

#59 (Console) Bug fix for membuf & Uart
  src/driver/console/console_membuf/console_membuf.c
  src/platform/mega_avr/common/hal/uart/uart.c
Labels: terravisor, cyancore framework, bug-low
