Repository VisorFolks/cyancore, pull requests merged in 2022-02, with the labels that each got.

#106 <Drivers> Updated driver architecture
  src/driver/console/console.c
  src/driver/console/console_membuf/earlycon_membuf.c
  src/driver/console/console_serial/console_serial.c
  src/driver/console/console_serial/earlycon_serial.c
  src/driver/interrupt/interrupt_controller.c
  src/driver/interrupt/plic/plic.c
  src/driver/interrupt/plic/plic_private.h
  src/driver/watchdog/watchdog.c
  src/include/driver/console.h
  src/include/driver/interrupt_controller.h
  src/include/driver/watchdog.h
  src/platform/mega_avr/common/platform/platform_wdt.c
Labels: enhancement, critical update, terravisor, cyancore framework, FR, bug-low

#110 Dev pranjal posix
  .vscode/settings.json
  src/arch/avr/8/common_5x_6/terravisor/include/arch.h
  src/arch/avr/8/common_5x_6/terravisor/include/avr.h
  src/arch/riscv/32/i/terravisor/include/arch.h
  src/arch/riscv/32/i/terravisor/include/riscv.h
  src/include/machine_call.h
  src/include/supervisor_call.h
  src/lib/libposix/include/posix/pthread.h
  src/lib/libposix/include/posix/sys/types.h
  src/lib/libposix/src/posix_pthread.c
  src/platform/mega_avr/atmega328p/include/plat_arch.h
  src/platform/mega_avr/common/platform/platform_resource.c
  src/platform/sifive/common_fe310/platform/platform_resource.c
  src/visor/supervisor/workers/scall/supervisory_call.c
  src/visor/terravisor/workers/mcall/machine_call.c
Labels: enhancement, cyancore framework, FR, bug-critical

#107 Dev akash sysloglib
  projects/demo_avr/config.mk
  projects/demo_avr_cpp/config.mk
  projects/demo_riscv/config.mk
  projects/demo_riscv/project.c
  projects/project.template/config.mk
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/arch/riscv/32/i/terravisor/arch.c
  src/driver/console/build.mk
  src/driver/console/console_serial/console_serial.c
  src/driver/console/console_serial/earlycon_serial.c
  src/driver/console/stdcon.c
  src/driver/console/stdlog_membuf/build.mk
  src/driver/console/stdlog_membuf/stdlog_membuf.c
  src/driver/driver.c
  src/driver/interrupt/plic/plic.c
  src/driver/watchdog/watchdog.c
  src/engine/build.mk
  src/engine/engine.c
  src/include/driver/console.h
  src/include/engine.h
  src/include/insignia.h
  src/include/status.h
  src/lib/build.mk
  src/lib/libc/build.mk
  src/lib/libc/include/stdbool.h
  src/lib/libc/include/stddev.h
  src/lib/libc/include/stdio.h
  src/lib/libc/printf.c
  src/lib/libc/stddev.c
  src/lib/libccfs/build.mk
  src/lib/libccfs/ccpfs.c
  src/lib/libccfs/include/ccpfs.h
  src/lib/libsyslog/build.mk
  src/lib/libsyslog/include/syslog.h
  src/lib/libsyslog/syslog.c
  src/platform/mega_avr/common/platform/platform.c
  src/platform/sifive/common_fe310/arch/platform_cpu.c
  src/platform/sifive/common_fe310/platform/platform.c
  src/sources.mk
Labels: bug-medium, enhancement, critical update, terravisor, cyancore framework, project, FR

#114 Development branch code_smell fix
  src/lib/libposix/include/posix/semaphore.h
  src/lib/libposix/include/posix/time.h
  src/lib/libposix/src/posix_semaphore.c
  src/lib/libposix/src/posix_time.c
Labels: bug-low

#117 <STDIN> Updated getch
  src/lib/libc/scanf.c
Labels: bug-low

#118 <syslog> Added debug logs
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  mk/path.mk
  mk/project.mk
  mk/qemu.mk
  mk/tc_get.mk
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/driver/console/console_serial/console_serial.c
  src/driver/console/console_serial/earlycon_serial.c
  src/driver/console/stdcon.c
  src/driver/interrupt/interrupt_controller.c
  src/driver/interrupt/plic/plic.c
  src/lib/libsyslog/include/syslog.h
  src/platform/mega_avr/atmega328p/resources/dp.c
  src/platform/mega_avr/common/hal/gpio/gpio.c
  src/platform/mega_avr/common/hal/uart/uart.c
  src/platform/mega_avr/common/hal/wdt/wdt.c
  src/platform/mega_avr/common/platform/platform.c
  src/platform/mega_avr/common/platform/platform_reset.c
  src/platform/mega_avr/common/platform/platform_resource.c
  src/platform/mega_avr/common/platform/platform_wdt.c
  src/platform/sifive/common_fe310/hal/gpio/gpio.c
  src/platform/sifive/common_fe310/platform/platform_reset.c
  src/platform/sifive/common_fe310/platform/platform_resource.c
  src/sources.mk
Labels: enhancement, terravisor

#120 Dev akash syslog
  mk/lobj.mk
  mk/obj.mk
  projects/demo_avr/config.mk
  projects/demo_avr/project.c
  projects/demo_avr_cpp/config.mk
  src/driver/console/console_serial/console_serial.c
  src/driver/console/console_serial/earlycon_serial.c
  src/driver/console/stdcon.c
  src/driver/console/stdlog_membuf/stdlog_membuf.c
  src/driver/driver.c
  src/driver/interrupt/interrupt_controller.c
  src/driver/interrupt/plic/plic.c
  src/lib/libsyslog/include/syslog.h
  src/lib/libsyslog/syslog.c
  src/platform/mega_avr/common/hal/gpio/gpio.c
  src/platform/mega_avr/common/hal/uart/uart.c
  src/platform/mega_avr/common/platform/platform.c
  src/platform/mega_avr/common/platform/platform_resource.c
  src/platform/mega_avr/common/platform/platform_wdt.c
  src/platform/sifive/common_fe310/platform/platform.c
  src/visor/terravisor/services/bootstrap/bootstrap.c
  src/visor/terravisor/workers/mcall/machine_call.c
Labels: enhancement, critical update, terravisor

#121 <DP> Updated irq node
  projects/demo_riscv/project.c
  src/arch/riscv/32/i/terravisor/arch.c
  src/driver/console/console_serial/console_serial.c
  src/driver/interrupt/interrupt.c
  src/driver/interrupt/plic/plic.c
  src/include/interrupt.h
  src/lib/libresource/include/dp/dp_device.h
  src/lib/libresource/include/dp/dp_module.h
  src/lib/libresource/include/dp/dp_system.h
  src/platform/mega_avr/atmega2560/resources/dp.c
  src/platform/mega_avr/atmega328p/resources/dp.c
  src/platform/mega_avr/common/hal/adc/adc.c
  src/platform/mega_avr/common/hal/timer/timer.c
  src/platform/mega_avr/common/hal/uart/uart.c
  src/platform/mega_avr/common/hal/wdt/wdt.c
  src/platform/mega_avr/common/platform/platform_wdt.c
  src/platform/sifive/common_fe310/hal/uart/uart.c
  src/platform/sifive/fe310g002/resources/dp.c
Labels: FR
