Repository VisorFolks/cyancore, pull requests merged in 2023-12, with the labels that each got.

#258 <RV32I> Fixed the order of assembler directives
  src/arch/riscv/32/i/terravisor/entry.S
Labels: terravisor, cyancore framework, bug-critical

#255 [README] Fixed hyperlink for discord server.
  README.md
Labels: bug-low

#260 Add support for strcpy
  src/lib/libc/include/string.h
  src/lib/libc/string.c
Labels: cyancore framework, FR

#261 <libc> strcpy is now a macro which uses strlcpy
  src/lib/libc/include/string.h
  src/lib/libc/string.c
Labels: bug-medium

#264 Update sonarcloud.yml
  .github/workflows/sonarcloud.yml
Labels: bug-low
