Repository VisorFolks/cyancore, pull requests merged in 2023-01, with the labels that each got.

#193 <Make> Moved heap and stack size spec to config.mk
  src/platform/mega_avr/atmega2560/config.mk
  src/platform/mega_avr/atmega2560/include/plat_mem.h
  src/platform/mega_avr/atmega328p/config.mk
  src/platform/mega_avr/atmega328p/include/plat_mem.h
  src/platform/sifive/fe310g002-bl/config.mk
  src/platform/sifive/fe310g002-bl/include/plat_mem.h
  src/platform/sifive/fe310g002/config.mk
  src/platform/sifive/fe310g002/include/plat_mem.h
Labels: enhancement, terravisor, FR

#189 <Mega-AVR> Add PWM HAL layer
  src/include/hal/pwm.h
  src/platform/mega_avr/common/hal/build.mk
  src/platform/mega_avr/common/hal/pwm/build.mk
  src/platform/mega_avr/common/hal/pwm/pwm.c
Labels: enhancement, terravisor, FR

#204 <RP2040> Add SIO platform support
  src/platform/pico/r2040/build.mk
  src/platform/pico/rp2040/build.mk
  src/platform/pico/rp2040/include/plat_mem.h
  src/platform/pico/rp2040/include/platform_sio.h
Labels: FR, supervisor

#205 <LibC> Add support for float in printf
  mk/elf.mk
  src/lib/libc/build.mk
  src/lib/libc/printf.c
  src/lib/libc/snprintf.c
  src/platform/mega_avr/common/build.mk
Labels: enhancement, critical update, cyancore framework, FR

#207 <CC_OS> Add functional callback hook for users
  src/include/visor/terravisor/cc_os/cc_os_tasks.h
  src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
  src/visor/terravisor/services/kernel/cc_os_task_idle.c
  src/visor/terravisor/services/kernel/cc_os_tasks.c
Labels: enhancement, terravisor, cc-os

#210 <Lint> Updated cppcheck flags and fixed code smells
  mk/lint.mk
  projects/demo_avr_cpp/project.cpp
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/arch/avr/8/common_5x_6/terravisor/include/arch.h
  src/driver/driver.c
  src/lib/libc/malloc_lite.c
  src/lib/libnmath/dsp/conv.c
  src/lib/libnmath/include/dsp/conv.h
  src/platform/mega_avr/common/platform/platform_timer.c
  src/platform/sifive/common_fe310/hal/prci/pll.c
  src/visor/terravisor/workers/mcall/machine_call.c
Labels: enhancement, cyancore framework, bug-critical

#214 <AVR8> Updated ctx mgnt frame to reduce stk use
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/arch/avr/8/common_5x_6/terravisor/asm.S
  src/arch/avr/8/common_5x_6/terravisor/include/avr.h
Labels: critical update, terravisor, FR

#217 <CC_OS> Add task ID
  src/include/visor/terravisor/cc_os/cc_os_tasks.h
  src/include/visor/terravisor/cc_os/utils/cc_os_sched.h
  src/visor/terravisor/services/kernel/cc_os_tasks.c
Labels: enhancement, cyancore framework, bug-critical, cc-os

#219 <Make> Fix for failure of build resume and updates
  mk/picotool.mk
  mk/qemu.mk
Labels: bug-medium, critical update, cyancore framework
