Repository VisorFolks/cyancore, pull requests merged in 2024-07, with the labels that each got.

#293 <ibex> Add support for exiting simulation
  projects/demo_ibex_ss/project.c
  src/platform/ibex/simple_system/platform/platform.c
Labels: enhancement, critical update, cyancore framework, project

#295 <TC> Add support for libmath
  README.md
  mk/lib.mk
  mk/tc.mk
  src/include/compiler_macros.h
  src/lib/libnmath/arithmetic/arithmetic.c
  src/lib/libnmath/build.mk
  src/lib/libnmath/include/nmath.h
  src/lib/libnmath/libm/build.mk
  src/lib/libnmath/libm/include/math.h
Labels: enhancement, critical update, cyancore framework, FR

#296 Bumping changes into stable.
  README.md
  mk/lib.mk
  mk/tc.mk
  projects/demo_ibex_ss/project.c
  src/include/compiler_macros.h
  src/lib/libnmath/arithmetic/arithmetic.c
  src/lib/libnmath/build.mk
  src/lib/libnmath/include/nmath.h
  src/lib/libnmath/libm/build.mk
  src/lib/libnmath/libm/include/math.h
  src/platform/ibex/simple_system/platform/platform.c
Labels: enhancement, critical update, FR

#300 [memcpy] fixed return value
  src/lib/libc/string.c
Labels: cyancore framework, bug-low

#302 <locks> Added support for bakerylock
  src/lib/build.mk
  src/lib/liblocks/bakerylock.c
  src/lib/liblocks/build.mk
  src/lib/liblocks/include/lock/bakerylock.h
  src/lib/liblocks/include/lock/lock.h
  src/lib/liblocks/include/lock/spinlock.h
Labels: enhancement, critical update, cyancore framework, FR

#305 [RV32I] bug fix for exception handler
  src/arch/riscv/32/i/terravisor/exception_handler.c
Labels: bug-critical

#309 Bumping changes into stable
  .github/CODEOWNERS
  README.md
  src/arch/riscv/32/i/terravisor/exception_handler.c
  src/lib/build.mk
  src/lib/libc/string.c
  src/lib/liblocks/bakerylock.c
  src/lib/liblocks/build.mk
  src/lib/liblocks/include/lock/bakerylock.h
  src/lib/liblocks/include/lock/lock.h
  src/lib/liblocks/include/lock/spinlock.h
Labels: critical update, cyancore framework, FR, bug-critical

#311 <qemu> Now using QEMU v9.0.0 release
  mk/qemu.mk
Labels: FR

#314 <QEMU-SiFive-E> Updated RTC Clock
  src/platform/sifive/qemu-sifive-e/resources/dp.c
Labels: critical update, bug-critical
