Repository VisorFolks/cyancore, pull requests merged in 2024-01, with the labels that each got.

#266 Bugfix/akashkollipara/status codes
  src/arch/riscv/32/i/terravisor/arch.c
  src/driver/driver.c
  src/driver/interrupt/plic/plic.c
  src/driver/sysclk/sysclk_prci/sysclk_prci.c
  src/include/status.h
  src/platform/mega_avr/common/hal/adc/adc.c
  src/platform/mega_avr/common/hal/gpio/gpio.c
  src/platform/mega_avr/common/hal/spi/spi.c
  src/platform/mega_avr/common/hal/timer/timer.c
  src/platform/mega_avr/common/hal/uart/uart.c
  src/platform/mega_avr/common/hal/wdt/wdt.c
  src/platform/sifive/common_fe310/hal/clint/clint.c
  src/platform/sifive/common_fe310/platform/plat_timer.c
  src/visor/terravisor/services/driver/timer.c
Labels: enhancement, bug-low

#272 Development
  .github/workflows/sonarcloud.yml
  .vscode/settings.json
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/arch/avr/8/common_5x_6/terravisor/include/arch.h
  src/arch/avr/8/common_5x_6/terravisor/init.c
  src/arch/riscv/32/i/terravisor/arch.c
  src/arch/riscv/32/i/terravisor/include/arch.h
  src/arch/riscv/32/i/terravisor/init.c
  src/driver/driver.c
  src/driver/interrupt/plic/plic.c
  src/driver/sysclk/sysclk_prci/sysclk_prci.c
  src/include/status.h
  src/lib/libc/include/string.h
  src/lib/libc/string.c
  src/platform/mega_avr/common/hal/adc/adc.c
  src/platform/mega_avr/common/hal/gpio/gpio.c
  src/platform/mega_avr/common/hal/spi/spi.c
  src/platform/mega_avr/common/hal/timer/timer.c
  src/platform/mega_avr/common/hal/uart/uart.c
  src/platform/mega_avr/common/hal/wdt/wdt.c
  src/platform/mega_avr/common/platform/platform.c
  src/platform/sifive/common_fe310/hal/clint/clint.c
  src/platform/sifive/common_fe310/platform/plat_timer.c
  src/platform/sifive/common_fe310/platform/platform.c
  src/platform/sifive/fe310g002-bl/config.mk
  src/platform/sifive/fe310g002/config.mk
  src/platform/sifive/qemu-sifive-e-bl/config.mk
  src/platform/sifive/qemu-sifive-e/config.mk
  src/visor/terravisor/services/driver/timer.c
Labels: documentation, enhancement, critical update, cyancore framework, FR, bug-critical

#268 <libresource> Add new macros to create SP and DP
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/arch/riscv/32/i/terravisor/arch.c
  src/lib/libc/include/stdio.h
  src/lib/libresource/include/dp.h
  src/lib/libresource/include/dp/dp_gpio.h
  src/lib/libresource/include/dp/dp_module.h
  src/lib/libresource/include/dp/dp_system.h
  src/lib/libresource/include/sp.h
  src/lib/libresource/include/sp/sp_visor.h
  src/platform/mega_avr/atmega2560/resources/dp.c
  src/platform/mega_avr/atmega2560/resources/sp.c
  src/platform/mega_avr/atmega328p/resources/dp.c
  src/platform/mega_avr/atmega328p/resources/sp.c
  src/platform/sifive/fe310g002-bl/resources/dp.c
  src/platform/sifive/fe310g002-bl/resources/sp.c
  src/platform/sifive/fe310g002/resources/dp.c
  src/platform/sifive/fe310g002/resources/sp.c
  src/platform/sifive/qemu-sifive-e-bl/resources/dp.c
  src/platform/sifive/qemu-sifive-e-bl/resources/sp.c
  src/platform/sifive/qemu-sifive-e/resources/dp.c
  src/platform/sifive/qemu-sifive-e/resources/sp.c
Labels: documentation, terravisor, cyancore framework, FR, bug-critical

#273 Feature/sagarladla/262 <lib c> add functions in stdlib
  src/lib/libc/include/stdlib.h
  src/lib/libc/strton.c
Labels: enhancement, cyancore framework

#279 sonar-cloud script updated to latest
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarcloud.yml.dep
Labels: bug-critical

#280 <Github Actions> Updated codeql version
  .github/workflows/github_ci.yml
Labels: critical update

#276 Release: Cyancore v1.4.0 [Boron]
  .github/workflows/github_ci.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarcloud.yml.dep
  README.md
  src/arch/avr/8/common_5x_6/terravisor/arch.c
  src/arch/riscv/32/i/terravisor/arch.c
  src/engine/banner.mk
  src/lib/libc/include/stdio.h
  src/lib/libc/include/stdlib.h
  src/lib/libc/strton.c
  src/lib/libresource/include/dp.h
  src/lib/libresource/include/dp/dp_gpio.h
  src/lib/libresource/include/dp/dp_module.h
  src/lib/libresource/include/dp/dp_system.h
  src/lib/libresource/include/sp.h
  src/lib/libresource/include/sp/sp_visor.h
  src/platform/mega_avr/atmega2560/resources/dp.c
  src/platform/mega_avr/atmega2560/resources/sp.c
  src/platform/mega_avr/atmega328p/resources/dp.c
  src/platform/mega_avr/atmega328p/resources/sp.c
  src/platform/sifive/fe310g002-bl/resources/dp.c
  src/platform/sifive/fe310g002-bl/resources/sp.c
  src/platform/sifive/fe310g002/resources/dp.c
  src/platform/sifive/fe310g002/resources/sp.c
  src/platform/sifive/qemu-sifive-e-bl/resources/dp.c
  src/platform/sifive/qemu-sifive-e-bl/resources/sp.c
  src/platform/sifive/qemu-sifive-e/resources/dp.c
  src/platform/sifive/qemu-sifive-e/resources/sp.c
Labels: documentation, enhancement, critical update, terravisor, cyancore framework, FR, bug-critical
