Repository VisorFolks/cyancore, pull requests merged in 2024-04, with the labels that each got.

#283 Dev/akashkollipara/87 arm cortex m0p
  mk/mk_helper.mk
  mk/tc.mk
  projects/demo_avr/config.mk
  projects/demo_avr_cpp/config.mk
  projects/demo_helios_avr/config.mk
  projects/demo_helios_riscv/config.mk
  projects/demo_qemu_sifive_e/config.mk
  projects/demo_riscv/config.mk
  projects/hifive1b_bl/config.mk
  projects/qemu_sifive_e_bl/config.mk
  src/arch/arm-m/32/common_v6_v7/supervisor/arch.c
  src/arch/arm-m/32/common_v6_v7/supervisor/arch_vectors.S
  src/arch/arm-m/32/common_v6_v7/supervisor/arch_vectors.c
  src/arch/arm-m/32/common_v6_v7/supervisor/asm.S
  src/arch/arm-m/32/common_v6_v7/supervisor/build.mk
  src/arch/arm-m/32/common_v6_v7/supervisor/exception_handler.c
  src/arch/arm-m/32/common_v6_v7/supervisor/include/arch.h
  src/arch/arm-m/32/common_v6_v7/supervisor/include/arm.h
  src/arch/arm-m/32/common_v6_v7/supervisor/init.c
  src/arch/riscv/32/i/terravisor/include/riscv.h
  src/platform/rpi/common_rp2/arch/build.mk
  src/platform/rpi/common_rp2/arch/platform_mem.c
  src/platform/rpi/common_rp2/build.mk
  src/platform/rpi/common_rp2/include/platform.h
  src/platform/rpi/common_rp2/platform/build.mk
  src/platform/rpi/common_rp2/platform/platform.c
  src/platform/rpi/common_rp2/platform/platform_reset.c
  src/platform/rpi/common_rp2/platform/platform_resource.c
  src/platform/rpi/common_rp2/sections.ld.sx
  src/platform/rpi/rp2040/config.mk
  src/platform/rpi/rp2040/include/plat_mem.h
Labels: enhancement, cyancore framework, FR

#285 AVR Driver Documentation Updates
  .vscode/settings.json
  projects/demo_avr_cpp/gpio.cpp
  projects/demo_avr_cpp/gpio.h
  projects/demo_avr_cpp/project.cpp
  src/driver/onboardled/onboardled.c
  src/platform/mega_avr/README.md
  src/platform/mega_avr/common/hal/adc/adc.c
  src/platform/mega_avr/common/hal/gpio/gpio.c
  src/platform/mega_avr/common/hal/pwm/pwm.c
  src/platform/mega_avr/common/hal/spi/spi.c
  src/platform/mega_avr/common/hal/timer/timer.c
  src/platform/mega_avr/common/hal/uart/uart.c
Labels: documentation, FR

#287 <1.4.1> Release Update
  .vscode/settings.json
  README.md
  mk/mk_helper.mk
  mk/tc.mk
  projects/demo_avr/config.mk
  projects/demo_avr_cpp/config.mk
  projects/demo_avr_cpp/gpio.cpp
  projects/demo_avr_cpp/gpio.h
  projects/demo_avr_cpp/project.cpp
  projects/demo_helios_avr/config.mk
  projects/demo_helios_riscv/config.mk
  projects/demo_qemu_sifive_e/config.mk
  projects/demo_riscv/config.mk
  projects/hifive1b_bl/config.mk
  projects/qemu_sifive_e_bl/config.mk
  src/arch/arm-m/32/common_v6_v7/supervisor/arch.c
  src/arch/arm-m/32/common_v6_v7/supervisor/arch_vectors.S
  src/arch/arm-m/32/common_v6_v7/supervisor/arch_vectors.c
  src/arch/arm-m/32/common_v6_v7/supervisor/asm.S
  src/arch/arm-m/32/common_v6_v7/supervisor/build.mk
  src/arch/arm-m/32/common_v6_v7/supervisor/exception_handler.c
  src/arch/arm-m/32/common_v6_v7/supervisor/include/arch.h
  src/arch/arm-m/32/common_v6_v7/supervisor/include/arm.h
  src/arch/arm-m/32/common_v6_v7/supervisor/init.c
  src/arch/riscv/32/i/terravisor/include/riscv.h
  src/driver/onboardled/onboardled.c
  src/engine/banner.mk
  src/platform/mega_avr/README.md
  src/platform/mega_avr/common/hal/adc/adc.c
  src/platform/mega_avr/common/hal/gpio/gpio.c
  src/platform/mega_avr/common/hal/pwm/pwm.c
  src/platform/mega_avr/common/hal/spi/spi.c
  src/platform/mega_avr/common/hal/timer/timer.c
  src/platform/mega_avr/common/hal/uart/uart.c
  src/platform/rpi/common_rp2/arch/build.mk
  src/platform/rpi/common_rp2/arch/platform_mem.c
  src/platform/rpi/common_rp2/build.mk
  src/platform/rpi/common_rp2/include/platform.h
  src/platform/rpi/common_rp2/platform/build.mk
  src/platform/rpi/common_rp2/platform/platform.c
  src/platform/rpi/common_rp2/platform/platform_reset.c
  src/platform/rpi/common_rp2/platform/platform_resource.c
  src/platform/rpi/common_rp2/sections.ld.sx
  src/platform/rpi/rp2040/config.mk
  src/platform/rpi/rp2040/include/plat_mem.h
Labels: documentation, enhancement, critical update, cyancore framework, FR, bug-critical, supervisor
